### ISSUE TITLE
Allow a forward proxy with username/password to be specified on a lookup call

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-commons#13]
In SoftLayer (and other cloud environments I suspect), all our outbound connections goes through a forward proxy, so this look up being an outbound call, needs to go thru that fwd proxy.  Furthermore, in our case we read the proxy values from a DB at runtime.  Consequently, we need a way to pass the proxy host, port, username and password to the smp-client on the lookup call which would then be used to make the http connection.   

Finally, we have multiple environments with different requirements.  Some are internal only and don't use a proxy, some use a proxy, but don't require userid and password, and some require the proxy and the userid/password.  It would be nice if the lookup ignores any parameters that have a null value, for example the proxy host and port could be present with some values, whereas username and password might not there there..so it should just use the proxy host and port in that case.

**Comment by phax** [comment]
Reminder to myself: see http://stackoverflow.com/questions/6962047/apache-httpclient-4-1-proxy-authentication as an example on how it could be done

**Comment by phax** [comment]
It was implemented, but I cannot test it....

**Comment by dhixon** [comment]
HI,

I am currently in the middle of setting up the Customer Test Environment 
for our new access point.  I will test it as soon as I finish that.

Thanks for adding that feature.

David Hixon
B2B Integration Architect
IBM Commerce Division - IBM US
(720) 396-9050
Tie 938-9050
Email:  dhixon@us.ibm.com

**Comment by phax** [comment]
I assume it's working - just let me know if not :)
