### ISSUE TITLE
Please provide the Dockerfile used to create the image in the repository

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-commons#14]
If possible, please include the Dockerfile used to create the image in the repo comments, or link to it.  It can be useful when we create customized Dockerfiles for a specific environment to know what is Dockerfile that we are "COPY"ing.

**Comment by phax** [comment]
I'm not sure whether I completly understand what you need.
The dockerfile is part of the repo - in the 'docker' folder...

**Comment by dhixon** [comment]
Hi. Yes, that is correct.  What I was suggesting is that in the "Full Description" area of the entry on Docker Hub  you reproduce the Dockerfile. I see your point though that it is only a couple of clicks to get to the Dockerfile on GitHub from your Docker Hub entry.  I am closing this issue as resolved.

**Comment by dhixon** [comment]
Resolved - Working as designed.
