### ISSUE TITLE
Make hostname and IP address part of the config file

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-commons#15]
As part of the registration GUI, the user must specify the host name and IP address of the system as part of the SMP registration.  Please put this in the config file, so that we can create custom Docker images that contain this information already because we include a COPY ../smp-server.properties ...
of a custom config file that contains these values.  This removes a step where the AppOps person has to log on as an administrator and then manually enter these values.

**Comment by phax** [comment]
Moved to different project
