### ISSUE TITLE
Missing classes CompleteServiceGroupType etc

### ISSUE THREAD

**Issue by dantam74** [phax/peppol-commons#24]
Hi and thanks for your effort of writing this library! I'm excited to start using it.

I've cloned your code and followed the build instructions. However there are classes missing (see attached screenshot) and the same names are found in xsd:s. I suspect that these classes are supposed to be generated from the xsd:s. Is there a build target or something similar that will generate the missing classes?

![missingclasses](https://user-images.githubusercontent.com/6025676/53889353-912b9c00-4026-11e9-802a-b7ba4b8d1db2.png)

**Comment by phax** [comment]
The missing classes are generated via `mvn generate-sources` - than add `target/generated-sources/xjc` as a source folder. They are created from XSD sources. happy coding :)

**Comment by dantam74** [comment]
Worked perfectly! Thanks :-)

**Comment by phax** [comment]
Super. I never check in the generated classes - so the same trick applies to other projects as well. But thanks for pointing out, that this needs better documentation :D
