### ISSUE TITLE
smp creation error is not visibile

### ISSUE THREAD

**Issue by fiorenzino** [phax/peppol-commons#28]
Hi
when we register a new participant using latest version of your API, we receive an error not really understandable:

com.sun.xml.ws.client.ClientTransportException: Il server ha inviato il codice di stato HTTP 404: Not Found

The real SOAP error (after a really long session of debug at low level):
```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode>
<faultstring>[ERR-100] The SMP 'PIT000xxxx' doesn't exist. [VH_QReaAzDt_QS23-b-D9n6RDbqmVWxxxxxxxxxxxxxxxxx]</faultstring><detail><NotFoundFault xmlns:ns2="http://busdox.org/transport/identifiers/1.0/" xmlns="http://busdox.org/serviceMetadata/locator/1.0/"><FaultMessage>[ERR-100] The SMP 'PIT000xxxx' doesn't exist.</FaultMessage></NotFoundFault></detail></soap:Fault></soap:Body></soap:Envelope>
```

The simple request:

```java
  @Test
public void test() throws Exception {
        ManageParticipantIdentifierServiceCaller aSMPClient = new ManageParticipantIdentifierServiceCaller(ESML.DIGIT_PRODUCTION);
        aSMPClient.setSSLSocketFactory(ssl());
        aSMPClient.create(smpId, new SimpleParticipantIdentifier("iso6523-actorid-upis", "9906:IT02252770066"));
    }
```

It should be usefull to wrap the soap original exception, in the message received at hight level.

Can you suggest how debug better that type of errors?

Best regard
Fiorenzo

**Comment by phax** [comment]
You need to register your SMP once at the SML.
If that succeeds, you can start creating service groups in the SML.
I will think about a thin wrapper around `ManageParticipantIdentifierServiceCaller` to catch the Exceptions more gracefully.

**Comment by fiorenzino** [comment]
This situation happened after certificates renewal. but we realized after some months (in the meantime no new participant registration).

**Comment by phax** [comment]
This request is the same as https://github.com/phax/phoss-smp/issues/33

**Comment by phax** [comment]
Short question. Is `PIT000xxxx` the SMP-ID your are using in production? This anyway seems to be the reason, why you cannot create the ServiceGroup. Please ensure to set the same SMP-ID (case sensitive) and retry.

**Comment by fiorenzino** [comment]
Yes. An example of an old partecipant in the same SMP subject:
https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=9906%3A04830660280&sml=auto&querybc=true&__querybc=true&action=perform

I think the SMP provider forgot to register/update the new smp id (received after some certificate upgrade) on SML.  Can i suggest to use your tool (https://peppol.helger.com/public/locale-en_US/menuitem-tools-smp-sml) to do that? This is UPDATE or REGISTER operation?
thanks for your help

**Comment by phax** [comment]
Well, the registered ID for this participant is `SMP2000000183` - I suggest not to update the ID, but instead  try to register with the existing ID.

Yes of course you can suggest my tool, but the upload of the JKS file should not be the preferred way....

**Comment by fiorenzino** [comment]
Where are you found this information (SMP2000000183)?
When you change the certificate (the openpeppol give you a new smp id), you must always do that procedure (register or update) or you should use the first SMP id?
What's your suggestion?

[you could add a new section on your website, to help little providers... :-) ]

**Comment by phax** [comment]
I have my secret sources ... just joking.
You posted the link to a specific participant, and I looked up the created DNS name:
> $nslookup B-88f56fcef6737362d58643fd27d04672.iso6523-actorid-upis.edelivery.tech.ec.europa.eu
> Server:  UnKnown
> Address:  192.168.1.1
> 
> Nicht autorisierende Antwort:
> Name:    peppolprod.westeurope.cloudapp.azure.com
> Address:  40.68.35.213
> Aliases:  B-88f56fcef6737362d58643fd27d04672.iso6523-actorid-upis.edelivery.tech.ec.europa.eu
>           **smp2000000183**.publisher.edelivery.tech.ec.europa.eu
>           peppolsmp.credemtel.it

The SMP ID should NEVER be changed. It is constant and must stay constant. Always use the first ID. If you choose [phoss-smp](https://github.com/phax/phoss-smp) you get all of this "out of the box" ;-)
What website do you mean? You mean at https://peppol.helger.com/public/locale-en_US/menuitem-tools-smp-sml or at https://peppol.helger.com/public/locale-en_US/menuitem-docs-setup-smp-ph ?

**Comment by fiorenzino** [comment]
The second! 
 https://peppol.helger.com

this is the bible for peppol user!

**Comment by fiorenzino** [comment]
It's not really clear the procedure. When you register yourself you receive a certificate for smp and one for AP. When you renew the certificate, it should be really clear.
you can write a good document for ths in you website https://peppol.helger.com

**Comment by phax** [comment]
Yes, I will try to write something on the "certificate update" process.

**Comment by phax** [comment]
Closed in favor of https://github.com/phax/peppol-practical/issues/6

**Comment by phax** [comment]
https://peppol.helger.com/public/menuitem-docs-peppol-cert-update
