### ISSUE TITLE
Running SML/K functions against the real SMK results in soap action errors

### ISSUE THREAD

**Issue by kukel** [phax/peppol-commons#36]
Due to integration reasons, we run our own SMP and so we have an SMP certificate and a registered SMP (on the SMK). We currently do not have implemented the migration of participants from/to our SMP, only the creation of new ones. Due to a takeover we'd like to migrate a customer from an external AP to our own and into our own SMP. 

Out of curiosity I thought to use your SML 'client' for a quick migration. I do get access to the  SMK (authentication and authorization is good) and I can read our own SMP settings from there. 

When trying the migration I get a soap action error so I thought to try to create a test particiapant id and see what happens then. Identical to the SMKFuncTest.java code.

    aPIClient.create (SMP_ID,
                          PeppolIdentifierFactory.INSTANCE.createParticipantIdentifierWithDefaultScheme ("9915:ourdummyid"));

 Unfortunately, the same sort of soap action error:

    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
        <soap:Body>
            <soap:Fault>
                <faultcode>soap:Server</faultcode>
                    <faultstring>The given SOAPAction http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/        :createIn does not match an operation.</faultstring>
            </soap:Fault>
        </soap:Body>
    </soap:Envelope>

I noticed the whitespace (both in the wsdl `ManageBusinessIdentifierService-1.0.wsdl` and generated java code `ManageBusinessIdentifierServiceSoap.jave` and compared with the read function that does work (ManageServiceMetadataService-1.0.wsdl and ManageServiceMetadataServiceSoap.java). There is no whitespace there so I removed that but still same error (without the whitespace in it). 

Now my colleagues told me we do not send a soap action at all and I tried changing the soap action in the wsdl and java code to an empty string and than I do get it registered. 

Version: 8.1.2-SNAPSHOT

**Comment by kukel** [comment]
Is it really a bug in peppol-commons? I personally think it is some quirk in he SML, don't you? I tried finding documentation that states where to selectively use soap actions and where not but could not find any.

**Comment by phax** [comment]
The blanks in the SOAP Action are there unintentionally, but they are effectively present in the service implementation from CEF.
For `ManageBusinessIdentifierService` the spaces are in (so managing participants), but for `ManageBusinessIdentifierService` no blanks are present.

To me the action looks good and that is the code that I'm using in the SMP. My only thoughts is, that you are passing the wrong URL in the `ManageParticipantIdentifierServiceCaller` constructor????

**Comment by kukel** [comment]
Yes, I also noticed them in another wsdl file. But I'm pretty sure I use the correct URL. Same as for reading our SMP configuration from the SML (K in this case) and the URL not explicitly passed on but taken from your `ESML.DIGIT_TEST`. 

This is the participant if I'm 'testing' with: https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=9915%3ASTEPCOM2&sml=digittest&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform

And I understand you are using this in the SMP (I checked that as well, sorry for not mentioning) but you also use the migration key generation there and that fails too on the SMK. So maybe a new software version was released on the SMK that is not really spec compliant anymore? Wonder how it is in production... Is there a prefix I could (ab)use for creating/testing a participant in `ESML.DIGIT_PRODUCTION`?

**Comment by kukel** [comment]
https://stackoverflow.com/questions/17987443/soapaction-header-missing-when-using-cxf

And I noticed somewhere in a 'change'/diff overview that there was a change from `soap` to `soap11`. Will try to find it again now I read the SO link

**Comment by kukel** [comment]
Yes! Might be related to the soap vs soap11. That is the difference between 'your' and 'their' wsdl... I compared with https://ec.europa.eu/cefdigital/code/projects/EDELIVERY/repos/bdmsl/browse/bdmsl-api/src/main/resources/ManageBusinessIdentifierService-1.0.wsdl 

![afbeelding](https://user-images.githubusercontent.com/833920/85513376-3d6a0b00-b5fb-11ea-9f71-7deb6c28a383.png)

**Comment by phax** [comment]
Did you compare against https://github.com/phax/peppol-commons/blob/master/peppol-sml-client/src/main/resources/WEB-INF/wsdl/ManageBusinessIdentifierService-1.0.wsdl#L151 ?
I do see the soap Action there.
The line break in CEFs implementation does not matter - it's is stripped off. But the 8 spaces are relevant.

The namespace prefix change from "soap11" to "soap" has no impact.

**Comment by kukel** [comment]
Yes I did and I would expect the namespace prefix change to not be of influence since it refers to the same namespace. Never the less I'm going to test. Have seen to many weird things with people not really understanding the technology (namespace etc), mainly in the .Net 'realm'

**Comment by phax** [comment]
Did you build the code yourself, or did you use the prebuild 8.1.2-SNAPSHOT binary version?
Since the SOAP action is part of the generated code, I just wanted to make sure, you are using the same wsimport version....

**Comment by phax** [comment]
Ah okay - based on your previous statement, you build from source and the action was correctly applied in the generated stub.
Are you eventually using a Proxy server?

**Comment by kukel** [comment]
I have no idea but when I changed the element names to soap11 for the 'create'  it worked WITH sending the soapAction. So to double check I reverted everything to 'head' and run it again, it works... 100% sure same request headers with same soapAction to same url with same content that now works... Beats me...

The migrationKey issue is still there though so not sure what fixed this but my requests were for sure identical.

**Comment by phax** [comment]
Shit happens ;-) Glad it works. The migration key issue is still open yes

**Comment by kukel** [comment]
I thought maybe 'they' reverted a deployment in the SMK that besides 'fixing' the soap action also fixed the migrationKey thing. Unfortunately not. But what feels weird is that it did happen and now works again... Can you see if there has maybe been an issue reported too?
