### ISSUE TITLE
Despite Map, for loop is used.

### ISSUE THREAD

**Issue by tmhide** [phax/peppol-commons#39]
https://github.com/phax/peppol-commons/blob/4524bcd5b4e3ade175a01dbe5e0f04069fee3eb0/peppol-id/src/main/java/com/helger/peppolid/peppol/doctype/PredefinedDocumentTypeIdentifierManager.java#L96

CODES is a Map. So you can get a value without using a for loop.
This is better in terms of performance.

Example
```
CODES.get(sDocTypeIDValue);
```

**Comment by phax** [comment]
Thanks for pointing that out - yes, for Peppol that is true.

**Comment by phax** [comment]
Part of 8.7.5 release
