### ISSUE TITLE
SMP Client documentation

### ISSUE THREAD

**Issue by francescodiperna** [phax/peppol-commons#40]
Hi to all, is there a documentation for the Client SMP ?

Kind regard

**Comment by phax** [comment]
Are you looking for the official specification of the HTTP API or a specification for my Java API?

The official Peppol SMP specification is at https://docs.peppol.eu/edelivery/

**Comment by francescodiperna** [comment]
Good morning Philip, I'm looking for the documentation of you java client.

Bye

**Comment by francescodiperna** [comment]
I'm looking in your client how I can check if a Service Group exists.

**Comment by phax** [comment]
Okay, so the checking for existance is not an explicit API.

Here is an example to read the Peppol "Service Group" for "9915:test" on the Peppol Test Network (SMK):

```java
  // The participant to query
   final IParticipantIdentifier aPI = PeppolIdentifierFactory.INSTANCE.createParticipantIdentifierWithDefaultScheme ("9915:test");

    // Peppol URL provider
    final SMPClientReadOnly aSMPClient = new SMPClientReadOnly (PeppolURLProvider.INSTANCE, aPI, ESML.DIGIT_TEST);
    assertEquals ("http://B-85008b8279e07ab0392da75fa55856a2.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/",
                  aSMPClient.getSMPHostURI ());

    // This performs the main HTTP request
    final ServiceGroupType aServiceGroup = aSMPClient.getServiceGroupOrNull (aPI);
    assertNotNull (aServiceGroup);
```

**Comment by francescodiperna** [comment]
Hi Philip, how I can create and delete business card via API?

**Comment by phax** [comment]
Therefore you can use the class `SMPClient` (without `ReadOnly`) - it has a `saveServiceGroup` and `deleteServiceGroup` methods.
But this API only works with phoss SMP and not with other SMP implementations, as the modifying API is not standardized.

**Comment by phax** [comment]
There is no library to do this atm.
There is only https://github.com/phax/phoss-directory/ from which you can use [phoss-directory-businesscard](https://github.com/phax/phoss-directory/tree/master/phoss-directory-businesscard) to build the Business Card data structure, but you need to make the HTTP POST call manually.

An easy way to do this, would be to subclass `SMPClient` yourself, add the BusinessCard data and then call `executeGenericRequest` (of SMPClient) like the other `save...` or `delete...` methods.
hth

**Comment by phax** [comment]
@francescodiperna Did you manage to solve the issue?

**Comment by francescodiperna** [comment]
Hi Philip, I used the library phoss-directory to build the PDBusinessEntity object but I do not understand how to send using executeGenericRequest, do you have some examples?

Kind regards

**Comment by phax** [comment]
You just serialize the

**Comment by francescodiperna** [comment]
But I have the object PDBusinessCard, can I convert it in XML?

**Comment by phax** [comment]
If you use an `PD3BusinessCardType` instead you can use the class `PD3BusinessCardMarshaller` to marshall this object to XML.

**Comment by francescodiperna** [comment]
Hi philip, I got an http error 302.
Does the URL is correct?

Bye

```
 inal BasicAuthClientCredentials SMP_CREDENTIALS = new BasicAuthClientCredentials (config.getSmpServerUsername(), config.getSmpServerPassword());	    	    
final String url = config.getSmpServerUrl() + "/businesscard/" + serviceGroup.getURIPercentEncoded();
final HttpPut aRequest = new HttpPut(config.getSmpServerUrl());
aRequest.addHeader (CHttpHeader.AUTHORIZATION, SMP_CREDENTIALS.getRequestValue());
aRequest.setEntity (new ByteArrayEntity (sBody , AbstractGenericSMPClient.CONTENT_TYPE_TEXT_XML));	    
smpClient.executeGenericRequest(aRequest, new SMPHttpResponseHandlerWriteOperations ());
```

**Comment by phax** [comment]
Instead of `new HttpPut(config.getSmpServerUrl());` use `new HttpPut(url);` :)

**Comment by francescodiperna** [comment]
ops :-)
