### ISSUE TITLE
SMP-CLIENT - SMPMarshallerSignedServiceMetadataType - error

### ISSUE THREAD

**Issue by afedi3** [phax/peppol-commons#57]
When i try to create:

`new SMPMarshallerSignedServiceMetadataType()`

I get the next error:

> com.helger.commons.state.EChange com.helger.commons.state.EChange.or(boolean)

We are currently using version 9.5.1. Any fix for this? I don't know if I am missing something.

Thanks!

**Comment by phax** [comment]
This seems like a problem in the dependencies.
If you use peppol-commons 9.5.1 you should also be using the ph-commons 11.1.6 version. Please make sure the dependencies are all set to "latest".

**Comment by afedi3** [comment]
I am using 11.1.6

<peppol-commons.version>9.5.1</peppol-commons.version>
 <ph-commons.version>11.1.6</ph-commons.version>
 
 
```
               <dependency>
			<groupId>com.helger.commons</groupId>
			<artifactId>ph-commons</artifactId>
			<version>${ph-commons.version}</version>
		</dependency>
		<dependency>
			<groupId>com.helger.commons</groupId>
			<artifactId>ph-datetime</artifactId>
			<version>${ph-commons.version}</version>
		</dependency>
		<dependency>
			<groupId>com.helger.commons</groupId>
			<artifactId>ph-jaxb</artifactId>
			<version>${ph-commons.version}</version>
		</dependency>
	
		
				<dependency>
			<groupId>com.helger.peppol</groupId>
			<artifactId>peppol-smp-client</artifactId>
			<version>${peppol-commons.version}</version>
		</dependency>
		<dependency>
			<groupId>com.helger.peppol</groupId>
			<artifactId>peppol-sbdh</artifactId>
			<version>${peppol-commons.version}</version>
		</dependency>
		<dependency>
			<groupId>com.helger.peppol</groupId>
			<artifactId>peppol-directory-businesscard</artifactId>
			<version>${peppol-commons.version}</version>
		</dependency>
```
Do you see any error? thanks!

**Comment by phax** [comment]
That looks all good.
Do you use some other dependency from me as well? As the order is relevant in Maven dependencies, it may even be that a third library is out of date.
Usually I recommend to do a `mvn dependency:tree` call to show the effective dependencies used.
hth

**Comment by afedi3** [comment]
Thanks! the problem was with:

			<groupId>com.helger</groupId>
			<artifactId>ph-ubl</artifactId>
			
I had two different versions of peppol-commons
